name: Build Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install basic dependencies
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install cmake bison flex
    - name: Build dependencies
      shell: bash
      run: |
        cd ci-scripts
        CC=clang CXX=clang++ ./install-deps.sh prefix 6
    - name: Build LatAnalyze
      shell: bash
      run: |
        cd ci-scripts
        CC=clang CXX=clang++ ./install-latan.sh prefix 6
